#! /bin/bash

#АВТОСТАРТ
sxhkd &
xsetroot -cursor_name left_ptr &
xrandr -s 1920x1080 &
nitrogen --restore &
polybar &
firefox &
nm-applet &

#numlockx &
#~/.config/polybar/launch.sh
#picom &


#ВОРКСПЕЙСЫ
bspc monitor -d                   

#РАМКИ И ГАПСЫ
bspc config border_width         2
bspc config window_gap          10

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#cba6f7"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНАЫ
bspc config presel_feedback_color "fd2e59"

#ПРИ ПОМОЩИ ЭТОЙ ХРЕНИ МОЖНО СДЕЛАТЬ ГАПСЫ ТОЛЬКО МЕЖДУ ОКНАМИ
#bspc config window_gap $gap;
#bspc config top_padding -$(($gap+2))
#bspc config left_padding -$(($gap+2))
#bspc config right_padding -$(($gap+4))
#bspc config bottom_padding $(($PANEL_HEIGHT-$gap))

#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5

#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	     false

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

#СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
#bspc config automatic_scheme	spiral

#ПРАВИЛА ОКОН
bspc rule -a firefox desktop='^1'
bspc rule -a TelegramDesktop state=floating follow=off desktop='4^'
bspc rule -a nitrogen state=floating follow=off 
#bspc rule -a Lutris state=floating follow=off rectangle=1200x700+360+190 desktop='^6' 
#bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
#bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
#bspc rule -a Inkscape desktop='^3'
#bspc rule -a Blender desktop='^2'
